[theme]
base="light"
primaryColor="#0077B6"           # Deep water blue (buttons, accents)
backgroundColor="#E6F2F8"        # Light blue background
secondaryBackgroundColor="#FFFFFF" # White content panels
textColor="#003049"              # Deep navy text
font="sans serif"
